// index.ts
/**
 * Main MTRL library exports
 * 
 * Includes both legacy "create*" functions and new "f*" functions for refactored components.
 * The transition to "f*" naming is being done incrementally.
 * 
 * @see src/FUNCTION_NAMING.md for details on the naming convention change
 */

// Import all functions - both legacy and new
import {
  // Legacy functions (all components)
  createLayout,
  createElement,
  createBadge,
  createBottomAppBar,
  createButton,
  createDatePicker,
  createFab,
  createExtendedFab,
  createSegmentedButton,
  createCard,
  fCarousel,
  createCheckbox,
  createChip,
  createChipSet,
  createDialog,
  createDivider,
  createList,
  createMenu,
  createNavigation,
  createNavigationSystem,
  createProgress,
  createRadios,
  createSearch,
  createSheet,
  createSlider,
  createSnackbar,
  createTabs,
  createTextfield,
  createTimePicker,
  createTooltip,
  createTopAppBar,
  
  // New functions (refactored components only)
  fLayout,
  fBadge,
  fBottomAppBar,
  fButton,
  fCard,
  fCardContent,
  fCardHeader,
  fCardActions,
  fCardMedia,
  fCheckbox,
  fChip,
  fChipSet,
  fDatePicker,
  fDialog,
  fDivider,
  fFab,
  fExtendedFab,
  fList,
  fListItem,
  fMenu,
  fProgress,
  fRadios,
  fSearch,
  fSegmentedButton,
  fSegment,
  fSheet,
  fSlider,
  fSnackbar,
  fSwitch,
  fTabs,
  fTab,
  fTextfield,
  fTimePicker,
  fTooltip,
  fTopAppBar
} from './src/index.js';

// Export all functions - both legacy and new
export {
  // Legacy functions (all components)
  createLayout,
  createElement,
  createBadge,
  createBottomAppBar,
  createButton,
  createDatePicker,
  createFab,
  createExtendedFab,
  createSegmentedButton,
  createCard,
  createCarousel,
  createCheckbox,
  createChip,
  createChipSet,
  createDialog,
  createDivider,
  createList,
  createMenu,
  createNavigation,
  createNavigationSystem,
  createProgress,
  createRadios,
  createSearch,
  createSheet,
  createSlider,
  createSnackbar,
  createSwitch,
  createTabs,
  createTextfield,
  createTimePicker,
  createTooltip,
  createTopAppBar,
  
  // New functions (refactored components only)
  fLayout,
  fBadge,
  fBottomAppBar,
  fButton,
  fCard,
  fCardContent,
  fCardHeader,
  fCardActions,
  fCardMedia,
  fCheckbox,
  fChip,
  fChipSet,
  fDatePicker,
  fDialog,
  fDivider,
  fFab,
  fExtendedFab,
  fList,
  fListItem,
  fMenu,
  fProgress,
  fRadios,
  fSearch,
  fSegmentedButton,
  fSegment,
  fSheet,
  fSlider,
  fSnackbar,
  fSwitch,
  fTabs,
  fTab,
  fTextfield,
  fTimePicker,
  fTooltip,
  fTopAppBar
};
