// src/constants.ts

// Import component constants
import {
  BADGE_VARIANTS,
  BADGE_COLORS,
  BADGE_POSITIONS,
  BADGE_MAX_CHARACTERS
} from './components/badge/constants';

import {
  FAB_POSITIONS as BOTTOM_APP_BAR_FAB_POSITIONS, 
  BOTTOM_APP_BAR_CLASSES, 
  DEFAULT_TRANSITION_DURATION
} from './components/bottom-app-bar/constants';

import {
  BUTTON_VARIANTS,
  BUTTON_TYPES,
  BUTTON_CLASSES,
  BUTTON_SIZES,
  BUTTON_SHAPES,
  DEFAULT_RIPPLE_CONFIG
} from './components/button/constants';

import {
  CARD_VARIANTS,
  CARD_ELEVATIONS,
  CARD_WIDTHS,
  CARD_CORNER_RADIUS,
  CARD_ASPECT_RATIOS,
  CARD_ACTION_ALIGNMENT,
  CARD_MEDIA_POSITION,
  CARD_CLASSES
} from './components/card/constants';

import {
  CHECKBOX_VARIANTS,
  CHECKBOX_LABEL_POSITION,
  CHECKBOX_STATES,
  CHECKBOX_CLASSES
} from './components/checkbox/constants';

import {
  CHIP_VARIANTS,
  CHIP_EVENTS,
  CHIPS_EVENTS
} from './components/chips/constants';

import {
  CHIP_CLASSES,
  CHIP_STATES
} from './components/chips/chip/constants';

import {
  DATEPICKER_VARIANTS,
  DATEPICKER_VIEWS,
  DATEPICKER_SELECTION_MODES,
  DAY_NAMES,
  MONTH_NAMES,
  MONTH_NAMES_SHORT,
  DEFAULT_DATE_FORMAT,
  DATEPICKER_CLASSES,
  DATEPICKER_EVENTS
} from './components/datepicker/constants';

import {
  DIALOG_SIZES,
  DIALOG_ANIMATIONS,
  DIALOG_FOOTER_ALIGNMENTS,
  DIALOG_EVENTS,
  DIALOG_CLASSES,
  DEFAULT_ANIMATION_DURATION,
  DEFAULT_Z_INDEX,
  DIALOG_BUTTON_VARIANTS,
  DEFAULT_CONFIRM_BUTTON_TEXT,
  DEFAULT_CANCEL_BUTTON_TEXT
} from './components/dialog/constants';

import {
  DIVIDER_ORIENTATIONS,
  DIVIDER_VARIANTS,
  DEFAULT_DIVIDER_THICKNESS,
  DEFAULT_INSET_VALUE,
  DIVIDER_CLASSES
} from './components/divider/constants';

import {
  EXTENDED_FAB_VARIANTS,
  EXTENDED_FAB_WIDTH,
  EXTENDED_FAB_POSITIONS,
  EXTENDED_FAB_ICON_POSITIONS,
  EXTENDED_FAB_CLASSES,
  EXTENDED_FAB_TYPES,
  EXTENDED_FAB_ANIMATIONS
} from './components/extended-fab/constants';

import {
  FAB_VARIANTS,
  FAB_SIZES,
  FAB_POSITIONS,
  FAB_CLASSES,
  FAB_TYPES,
  FAB_ICON_SIZES,
  FAB_ANIMATIONS
} from './components/fab/constants';

import {
  LIST_DEFAULTS,
  LIST_TYPES,
  LIST_SELECTION_MODES,
  LIST_EVENTS,
  LIST_SCROLL_POSITIONS,
  LIST_CLASSES
} from './components/list/constants';

import {
  MENU_POSITION,
  MENU_DEFAULTS,
  MENU_INTERACTION_TYPES,
  MENU_ITEM_TYPES,
  MENU_EVENTS,
  MENU_CLASSES
} from './components/menu/constants';

import {
  NAV_VARIANTS,
  NAV_POSITIONS,
  NAV_BEHAVIORS,
  NAV_ITEM_STATES,
  NAV_EVENTS,
  NAV_DEFAULTS,
  NAV_CLASSES
} from './components/navigation/constants';

import {
  PROGRESS_VARIANTS,
  PROGRESS_EVENTS,
  PROGRESS_DEFAULTS,
  PROGRESS_CLASSES,
  PROGRESS_THICKNESS,
  PROGRESS_SHAPES
} from './components/progress/constants';

import {
  RADIO_STATES,
  RADIO_DIRECTIONS,
  RADIO_VARIANTS,
  RADIO_LABEL_POSITIONS,
  RADIO_SIZES,
  RADIO_EVENTS,
  RADIO_DEFAULTS,
  RADIO_CLASSES
} from './components/radios/constants';

import {
  SEARCH_VARIANTS,
  SEARCH_STATES,
  SEARCH_EVENTS,
  SEARCH_ICONS,
  SEARCH_DEFAULTS,
  SEARCH_CLASSES
} from './components/search/constants';

import {
  SEGMENTED_BUTTON_MODES,
  SEGMENTED_BUTTON_DENSITY,
  SEGMENTED_BUTTON_EVENTS,
  SEGMENTED_BUTTON_DEFAULTS,
  SEGMENTED_BUTTON_ICONS,
  SEGMENTED_BUTTON_CLASSES
} from './components/segmented-button/constants';

import {
  SELECT_VARIANTS,
  SELECT_PLACEMENT,
  SELECT_INTERACTION,
  SELECT_EVENTS,
  SELECT_ICONS,
  SELECT_DEFAULTS,
  SELECT_CLASSES
} from './components/select/constants';

import {
  SHEET_VARIANTS,
  SHEET_POSITIONS,
  SHEET_EVENTS,
  SHEET_ELEVATION,
  SHEET_DEFAULTS,
  SHEET_ANIMATION,
  SHEET_GESTURE,
  SHEET_CLASSES
} from './components/sheet/constants';

import {
  SLIDER_COLORS,
  SLIDER_SIZES,
  SLIDER_EVENTS,
  SLIDER_POSITIONS,
  SLIDER_DEFAULTS,
  SLIDER_CLASSES
} from './components/slider/constants';

import {
  SNACKBAR_VARIANTS,
  SNACKBAR_POSITIONS,
  SNACKBAR_STATES,
  SNACKBAR_EVENTS,
  SNACKBAR_DEFAULTS,
  SNACKBAR_CLASSES
} from './components/snackbar/constants';

import {
  SWITCH_LABEL_POSITIONS,
  SWITCH_STATES,
  SWITCH_EVENTS,
  SWITCH_DEFAULTS,
  SWITCH_CLASSES
} from './components/switch/constants';

import {
  TAB_VARIANTS,
  TAB_STATES,
  TAB_INDICATOR_WIDTH_STRATEGIES,
  TAB_EVENTS,
  TABS_EVENTS,
  TABS_DEFAULTS,
  TABS_CLASSES,
  TAB_CLASSES
} from './components/tabs/constants';

import {
  TEXTFIELD_VARIANTS,
  TEXTFIELD_SIZES,
  TEXTFIELD_STATES,
  TEXTFIELD_TYPES,
  TEXTFIELD_EVENTS,
  TEXTFIELD_DEFAULTS,
  TEXTFIELD_CLASSES
} from './components/textfield/constants';

import {
  TIMEPICKER_TYPES,
  TIMEPICKER_ORIENTATIONS,
  TIMEPICKER_FORMATS,
  TIMEPICKER_PERIODS,
  TIMEPICKER_EVENTS,
  TIMEPICKER_DIAL,
  TIMEPICKER_VALUES,
  TIMEPICKER_Z_INDEX,
  TIMEPICKER_DEFAULTS,
  TIMEPICKER_CLASSES
} from './components/timepicker/constants';

import {
  TOOLTIP_POSITIONS,
  TOOLTIP_VARIANTS,
  TOOLTIP_EVENTS,
  TOOLTIP_DEFAULTS,
  TOOLTIP_CLASSES
} from './components/tooltip/constants';

import {
  TOP_APP_BAR_TYPES,
  TOP_APP_BAR_STATES,
  TOP_APP_BAR_DEFAULTS,
  TOP_APP_BAR_CLASSES
} from './components/top-app-bar/constants';

// Re-export all constants
export {
  // Badge
  BADGE_VARIANTS,
  BADGE_COLORS,
  BADGE_POSITIONS,
  BADGE_MAX_CHARACTERS,

  // Bottom App Bar
  BOTTOM_APP_BAR_FAB_POSITIONS, 
  BOTTOM_APP_BAR_CLASSES, 
  DEFAULT_TRANSITION_DURATION,

  // Button
  BUTTON_VARIANTS,
  BUTTON_TYPES,
  BUTTON_CLASSES,
  BUTTON_SIZES,
  BUTTON_SHAPES,
  DEFAULT_RIPPLE_CONFIG,
  
  // Card
  CARD_VARIANTS,
  CARD_ELEVATIONS,
  CARD_WIDTHS,
  CARD_CORNER_RADIUS,
  CARD_ASPECT_RATIOS,
  CARD_ACTION_ALIGNMENT,
  CARD_MEDIA_POSITION,
  CARD_CLASSES,
  
  // Checkbox
  CHECKBOX_VARIANTS,
  CHECKBOX_LABEL_POSITION,
  CHECKBOX_STATES,
  CHECKBOX_CLASSES,
  
  // Chips
  CHIP_VARIANTS,
  CHIP_EVENTS,
  CHIPS_EVENTS,
  CHIP_CLASSES,
  CHIP_STATES,
  
  // DatePicker
  DATEPICKER_VARIANTS,
  DATEPICKER_VIEWS,
  DATEPICKER_SELECTION_MODES,
  DAY_NAMES,
  MONTH_NAMES,
  MONTH_NAMES_SHORT,
  DEFAULT_DATE_FORMAT,
  DATEPICKER_CLASSES,
  DATEPICKER_EVENTS,
  
  // Dialog
  DIALOG_SIZES,
  DIALOG_ANIMATIONS,
  DIALOG_FOOTER_ALIGNMENTS,
  DIALOG_EVENTS,
  DIALOG_CLASSES,
  DEFAULT_ANIMATION_DURATION,
  DEFAULT_Z_INDEX,
  DIALOG_BUTTON_VARIANTS,
  DEFAULT_CONFIRM_BUTTON_TEXT,
  DEFAULT_CANCEL_BUTTON_TEXT,
  
  // Divider
  DIVIDER_ORIENTATIONS,
  DIVIDER_VARIANTS,
  DEFAULT_DIVIDER_THICKNESS,
  DEFAULT_INSET_VALUE,
  DIVIDER_CLASSES,
  
  // Extended FAB
  EXTENDED_FAB_VARIANTS,
  EXTENDED_FAB_WIDTH,
  EXTENDED_FAB_POSITIONS,
  EXTENDED_FAB_ICON_POSITIONS,
  EXTENDED_FAB_CLASSES,
  EXTENDED_FAB_TYPES,
  EXTENDED_FAB_ANIMATIONS,
  
  // FAB
  FAB_VARIANTS,
  FAB_SIZES,
  FAB_POSITIONS,
  FAB_CLASSES,
  FAB_TYPES,
  FAB_ICON_SIZES,
  FAB_ANIMATIONS,
  
  // List
  LIST_DEFAULTS,
  LIST_TYPES,
  LIST_SELECTION_MODES,
  LIST_EVENTS,
  LIST_SCROLL_POSITIONS,
  LIST_CLASSES,
  
  // Menu
  MENU_POSITION,
  MENU_DEFAULTS,
  MENU_INTERACTION_TYPES,
  MENU_ITEM_TYPES,
  MENU_EVENTS,
  MENU_CLASSES,
  
  // Navigation
  NAV_VARIANTS,
  NAV_POSITIONS,
  NAV_BEHAVIORS,
  NAV_ITEM_STATES,
  NAV_EVENTS,
  NAV_DEFAULTS,
  NAV_CLASSES,
  
  // Progress
  PROGRESS_VARIANTS,
  PROGRESS_EVENTS,
  PROGRESS_DEFAULTS,
  PROGRESS_CLASSES,
  
  // Radio
  RADIO_STATES,
  RADIO_DIRECTIONS,
  RADIO_VARIANTS,
  RADIO_LABEL_POSITIONS,
  RADIO_SIZES,
  RADIO_EVENTS,
  RADIO_DEFAULTS,
  RADIO_CLASSES,
  
  // Search
  SEARCH_VARIANTS,
  SEARCH_STATES,
  SEARCH_EVENTS,
  SEARCH_ICONS,
  SEARCH_DEFAULTS,
  SEARCH_CLASSES,
  
  // Segmented Button
  SEGMENTED_BUTTON_MODES,
  SEGMENTED_BUTTON_DENSITY,
  SEGMENTED_BUTTON_EVENTS,
  SEGMENTED_BUTTON_DEFAULTS,
  SEGMENTED_BUTTON_ICONS,
  SEGMENTED_BUTTON_CLASSES,
  
  // Select
  SELECT_VARIANTS,
  SELECT_PLACEMENT,
  SELECT_INTERACTION,
  SELECT_EVENTS,
  SELECT_ICONS,
  SELECT_DEFAULTS,
  SELECT_CLASSES,
  
  // Sheet
  SHEET_VARIANTS,
  SHEET_POSITIONS,
  SHEET_EVENTS,
  SHEET_ELEVATION,
  SHEET_DEFAULTS,
  SHEET_ANIMATION,
  SHEET_GESTURE,
  SHEET_CLASSES,
  
  // Slider
  SLIDER_COLORS,
  SLIDER_SIZES,
  SLIDER_EVENTS,
  SLIDER_POSITIONS,
  SLIDER_DEFAULTS,
  SLIDER_CLASSES,
  
  // Snackbar
  SNACKBAR_VARIANTS,
  SNACKBAR_POSITIONS,
  SNACKBAR_STATES,
  SNACKBAR_EVENTS,
  SNACKBAR_DEFAULTS,
  SNACKBAR_CLASSES,
  
  // Switch
  SWITCH_LABEL_POSITIONS,
  SWITCH_STATES,
  SWITCH_EVENTS,
  SWITCH_DEFAULTS,
  SWITCH_CLASSES,
  
  // Tabs
  TAB_VARIANTS,
  TAB_STATES,
  TAB_INDICATOR_WIDTH_STRATEGIES,
  TAB_EVENTS,
  TABS_EVENTS,
  TABS_DEFAULTS,
  TABS_CLASSES,
  TAB_CLASSES,
  
  // Textfield
  TEXTFIELD_VARIANTS,
  TEXTFIELD_SIZES,
  TEXTFIELD_STATES,
  TEXTFIELD_TYPES,
  TEXTFIELD_EVENTS,
  TEXTFIELD_DEFAULTS,
  TEXTFIELD_CLASSES,
  
  // Timepicker
  TIMEPICKER_TYPES,
  TIMEPICKER_ORIENTATIONS,
  TIMEPICKER_FORMATS,
  TIMEPICKER_PERIODS,
  TIMEPICKER_EVENTS,
  TIMEPICKER_DIAL,
  TIMEPICKER_VALUES,
  TIMEPICKER_Z_INDEX,
  TIMEPICKER_DEFAULTS,
  TIMEPICKER_CLASSES,
  
  // Tooltip
  TOOLTIP_POSITIONS,
  TOOLTIP_VARIANTS,
  TOOLTIP_EVENTS,
  TOOLTIP_DEFAULTS,
  TOOLTIP_CLASSES,
  
  // Top App Bar
  TOP_APP_BAR_TYPES,
  TOP_APP_BAR_STATES,
  TOP_APP_BAR_DEFAULTS,
  TOP_APP_BAR_CLASSES
};
